version: "3.8"
services:
  broadcast_channel:
    image: redis:5
  opal_server:
    image: authorizon/opal-server:latest
    environment:
      # the broadcast backbone uri used by opal server workers (see comments above for: broadcast_channel)
      - OPAL_BROADCAST_URI=redis://broadcast_channel:6379
      - UVICORN_NUM_WORKERS=4
      - OPAL_POLICY_REPO_URL=https://github.com/permitio/opal-example-policy-repo
      - OPAL_POLICY_REPO_POLLING_INTERVAL=30
      - OPAL_DATA_CONFIG_SOURCES={"config":{"entries":[{"topics":["policy_data"],"dst_path":"cities","url":"file:/db/opal.db","config":{"fetcher":"SQLiteFetchProvider","query":"SELECT * FROM city;"}}]}}
    ports:
      - "7002:7002"
    depends_on:
      - broadcast_channel

  opal_client:
    build:
      context: .
    environment:
      - OPAL_SERVER_URL=http://opal_server:7002
      - OPAL_FETCH_PROVIDER_MODULES=opal_common.fetcher.providers,opal_fetcher_sqlite.provider
      - OPAL_INLINE_OPA_LOG_FORMAT=http
        # update callbacks config ----------------------------------
        # this var turns on a callback (HTTP call to a configurable url) after every successful data update
        # and allows you to track which data updates completed successfully and were saved to OPA cache.
      - OPAL_SHOULD_REPORT_ON_DATA_UPDATES=True
        # we configure a callback to go to a default location in the OPAL server, but you can configure
        # a callback to any url you'd like. Each callback is either the url alone, or a tuple of
        # (url, HttpFetcherConfig).
        # We show here both ways to configure the same endpoint, one of them demonstrate how to
        # add extra HTTP headers (the header shown is ignored, only here for example).
      - OPAL_DEFAULT_UPDATE_CALLBACKS={"callbacks":["http://opal_server:7002/data/callback_report"]}
        # - OPAL_DEFAULT_UPDATE_CALLBACKS={"callbacks":[("http://opal_server:7002/data/callback_report",{"headers":{"X-My-Token":"token"}})]}
        # OPAL can load a special policy into OPA that acts as a healthcheck policy (Not directly related to the callback feature).
        # This policy defines two opa rules you can query:
        # ready rule (POST http://localhost:8181/data/system/opal/ready): signals that OPA is ready to accept authorization queries.
        # healthy rule (POST http://localhost:8181/data/system/opal/ready): signals that the last policy and data updates succeeded.
      - OPAL_OPA_HEALTH_CHECK_POLICY_ENABLED=True
        # end of update callbacks config ---------------------------
    ports:
      - "7000:7000"
      - "8181:8181"
    depends_on:
      - opal_server
    volumes:
      - ./opal.db:/db/opal.db
      # this command is not necessary when deploying OPAL for real, it is simply a trick for dev environments
    # to make sure that opal-server is already up before starting the client.
    command: sh -c "/start.sh"