version: "3.8"
services:
  opal_server:
    image: authorizon/opal-server:latest
    environment:
      - UVICORN_NUM_WORKERS=4
      - OPAL_POLICY_REPO_URL=https://github.com/permitio/opal-example-policy-repo
      - OPAL_POLICY_REPO_POLLING_INTERVAL=30
      - OPAL_DATA_CONFIG_SOURCES='{"config":{"entries":[{"topics":["policy_data"],"dst_path":"cities","url":"file:/db/opal.db","config":{"fetcher":"SQLiteFetchProvider","query":"SELECT * FROM city;"}}]}}'
    ports:
      - "7002:7002"

  opal_client:
    build:
      context: .
    environment:
      - OPAL_SERVER_URL=http://opal_server:7002
      - OPAL_FETCH_PROVIDER_MODULES=opal_common.fetcher.providers,opal_fetcher_sqlite.provider
      - OPAL_INLINE_OPA_LOG_FORMAT=http
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "7000:7000"
      - "8181:8181"
    depends_on:
      - opal_server
    volumes:
      - ./opal.db:/db/opal.db
        # this command is not necessary when deploying OPAL for real, it is simply a trick for dev environments
    # to make sure that opal-server is already up before starting the client.
    command: sh -c "/start.sh"
